cdadd_newline = true
scan_timeout = 100
command_timeout = 1000

[character]
success_symbol = "[âœ](bold green)" # ã‚³ãƒãƒ³ãƒ‰æˆåŠŸæ™‚
error_symbol = "[âœ](bold red)"    #ã‚³ãƒãƒ³ãƒ‰å¤±æ•—æ™‚

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$userğŸŒ±]($style) "
disabled = false
show_always = true

[time]
disabled = true
format = "[$time]($style) "
use_12hr = false

### git
[git_status]
disabled = true

### language
## ã‚·ãƒ³ãƒœãƒ«å¤‰æ›´
[conda]
symbol = "ï„Œ  "

[dart]
symbol = "î˜  "

[docker_context]
symbol = "ïŒˆ  "

[elixir]
symbol = "î‰µ  "

[git_branch]
symbol = "ïˆ "

[golang]
symbol = "î˜§  "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰–  "

[julia]
symbol = "î˜¤  "

[nodejs]
symbol = "îœ˜  "

[nix_shell]
symbol = "ï‹œ  "

[perl]
symbol = "î©  "

[php]
symbol = "î˜ˆ  "

[python]
symbol = "î˜†  "

[ruby]
symbol = "îˆ¾  "

[rust]
symbol = "î¨  "

[scala]
symbol = "îœ·  "

[shlvl]
symbol = "ï„   "

[swift]
symbol = "ï¯£ "